### ISSUE TITLE
example fails with "Can't use string ("1/8") as a HASH ref"

### ISSUE THREAD

**Issue by tomk3003** [oetiker/mojolicious-plugin-spnego#2]
running the example from the Synopsis gives:

`[Tue Oct 18 13:28:16 2016] [error] Can't use string ("1/8") as a HASH ref while
"strict refs" in use at C:/Progs/Perl5222/perl/site/lib/Mojolicious/Plugin/SPNEG
O.pm line 22, <DATA> line 755.`

This is due to line 17:

`my $helper_cfg = ref ${_}[0] ? %{${_}[0]} : { @_ };`

 witch should be

`my $helper_cfg = ref ${_}[0] ? ${_}[0] : { @_ };`

**Comment by FROGGS** [comment]
This appears to be solved already.
